# Generated by Django 2.2.10 on 2020-03-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200319_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
